const LIB_FIELD_LABELS = {
  avatar: '照片', company: '工作单位', position: '职位', phone: '主电话', phones: '多个电话', email: '主邮箱', emails: '多个邮箱',
  wechat: '微信', educationBackground: '教育经历', workExperience: '工作经历', socialPositions: '社会职务', skills: '技能',
  jobLevel: '级别', industry: '行业', field: '领域', gender: '性别', residentialAddress: '住宅地址', hometownAddress: '老家地址',
  birthplace: '籍贯', qq: 'QQ', website: '网站', linkedin: 'LinkedIn', fax: '传真', tags: '标签', remark: '备注'
};
const DEFAULT_FIELD_SETTINGS = Object.fromEntries(Object.keys(LIB_FIELD_LABELS).map(k => [k, !['residentialAddress','hometownAddress','birthplace','qq','website','linkedin','fax'].includes(k)]));
function parseMaybeJson(v, fallback = []) { if (!v) return fallback; if (Array.isArray(v)) return v; try { return JSON.parse(v); } catch { return fallback; } }
function fieldSettingsOf(lib) { return { ...DEFAULT_FIELD_SETTINGS, ...(parseMaybeJson(lib.fieldSettings, {}) || {}) }; }
function roleCan(role, min) { const n = { admin:4, manager:3, editor:2, viewer:1 }; return (n[role] || 0) >= (n[min] || 0); }
function renderField(label, value) { if (value === undefined || value === null || value === '' || (Array.isArray(value) && !value.length)) return ''; return `<div class="info-label">${label}</div><div>${Array.isArray(value) ? value.map(escapeHtml).join('<br>') : escapeHtml(value)}</div>`; }
function renderArraySection(title, arr, fmt) { arr = parseMaybeJson(arr, []); if (!arr.length) return ''; return `<div class="card-title" style="margin-top:18px">${title}</div>${arr.map(fmt).join('')}`; }

async function loadLibraries() {
  const el = document.getElementById('page-libraries');
  el.innerHTML = `<div class="toolbar"><h2 style="margin:0;flex:1">📇 名片库</h2><button class="btn btn-primary" onclick="showCreateLibrary()">+ 新建名片库</button></div><div class="card"><div id="libs-list">加载中...</div></div>`;
  try {
    const libs = await api('/libraries');
    document.getElementById('libs-list').innerHTML = libs.length ? `<table><thead><tr><th>名称</th><th>说明</th><th>角色</th><th>成员</th><th>名片</th><th>操作</th></tr></thead><tbody>${libs.map(l => `
      <tr><td><strong>${escapeHtml(l.name)}</strong></td><td>${escapeHtml(l.description || '-')}</td><td><span class="badge badge-${l.role}">${roleLabel(l.role)}</span></td><td>${l._count?.members || 0}</td><td>${l._count?.cards || 0}</td><td>
        ${roleCan(l.role,'admin') ? `<button class="btn-sm outline" onclick="editLibrary(${l.id})">编辑</button><button class="btn-sm blue" onclick="showLibFields(${l.id})">字段设置</button><button class="btn-sm outline" onclick="showLibMembers(${l.id})">成员</button><button class="btn-sm danger" onclick="deleteLib(${l.id},'${escapeHtml(l.name)}')">删除</button>` : '<span style="color:#999">只读访问</span>'}
      </td></tr>`).join('')}</tbody></table>` : '<p style="color:#999">暂无名片库</p>';
  } catch (e) { document.getElementById('libs-list').innerHTML = `<div class="error">${e.message}</div>`; }
}
function showCreateLibrary() {
  openModal('新建名片库', `<input class="input" id="lib-name" placeholder="名片库名称"><textarea id="lib-desc" placeholder="说明"></textarea><div class="modal-footer"><button class="btn btn-muted" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="createLibrary()">创建</button></div>`);
}
async function createLibrary() { try { await api('/libraries', { method:'POST', body:{ name:document.getElementById('lib-name').value, description:document.getElementById('lib-desc').value } }); toast('已创建','success'); closeModal(); loadLibraries(); } catch(e){ toast(e.message,'error'); } }
async function editLibrary(id) { const lib = await api(`/libraries/${id}`); openModal('编辑名片库', `<input class="input" id="lib-name" value="${escapeHtml(lib.name)}"><textarea id="lib-desc">${escapeHtml(lib.description || '')}</textarea><div class="modal-footer"><button class="btn btn-muted" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="saveLibrary(${id})">保存</button></div>`); }
async function saveLibrary(id) { try { await api(`/libraries/${id}`, { method:'PUT', body:{ name:document.getElementById('lib-name').value, description:document.getElementById('lib-desc').value } }); toast('已保存','success'); closeModal(); loadLibraries(); } catch(e){ toast(e.message,'error'); } }
async function deleteLib(id, name) { confirmLayer({ title:'删除名片库', tone:'soft', message:`确定删除「${name}」？名片和成员关系会一起删除。`, okText:'确认删除', onOk: async()=>{ await api(`/libraries/${id}`, { method:'DELETE' }); toast('已删除','success'); loadLibraries(); }}); }
async function showLibFields(id) {
  const lib = await api(`/libraries/${id}`); const settings = fieldSettingsOf(lib);
  openModal('名片库字段显示设置', `<p style="color:#666;margin-bottom:12px">关闭后，普通查看者看不到该字段；库管理员、经理和名片本人仍可见。</p><div class="field-grid">${Object.entries(LIB_FIELD_LABELS).map(([k,v]) => `<label class="field-check"><input type="checkbox" data-field="${k}" ${settings[k] ? 'checked' : ''}> ${v}</label>`).join('')}</div><div class="modal-footer"><button class="btn btn-muted" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="saveLibFields(${id})">保存</button></div>`, 'large');
}
async function saveLibFields(id) { const obj = {}; document.querySelectorAll('#modal-body input[data-field]').forEach(i => obj[i.dataset.field] = i.checked); try { await api(`/libraries/${id}`, { method:'PUT', body:{ fieldSettings: obj } }); toast('字段设置已保存','success'); closeModal(); loadLibraries(); } catch(e){ toast(e.message,'error'); } }
async function showLibMembers(libId) {
  const members = await api(`/libraries/${libId}/members`).catch(e => { toast(e.message,'error'); return []; });
  openModal('成员管理', `<div style="margin-bottom:12px">${members.map(m => `<div style="display:flex;align-items:center;gap:8px;padding:8px 0;border-bottom:1px solid var(--border)"><span style="flex:1">${escapeHtml(m.user.nickname || m.user.username)} <small style="color:#999">#${m.user.id}</small></span><span class="badge badge-${m.role}">${roleLabel(m.role)}</span><button class="btn-sm outline" onclick="showChangeMemberRole(${libId},${m.id},'${m.role}')">改角色</button><button class="btn-sm danger" onclick="removeMember(${libId},${m.id})">移除</button></div>`).join('') || '<p style="color:#999">暂无成员</p>'}</div><div style="display:flex;gap:8px"><input class="input" id="new-member-id" placeholder="用户 ID" style="flex:1;margin:0"><select id="new-member-role"><option value="viewer">只读</option><option value="editor">编辑</option><option value="manager">经理</option><option value="admin">库管理员</option></select><button class="btn btn-primary" onclick="addMember(${libId})">添加</button></div>`);
}
async function addMember(libId) { const userId = parseInt(document.getElementById('new-member-id').value); const role = document.getElementById('new-member-role').value; if (!userId) return toast('请输入用户 ID','error'); try { await api(`/libraries/${libId}/members`, { method:'POST', body:{ userId, role } }); toast('已添加','success'); showLibMembers(libId); } catch(e){ toast(e.message,'error'); } }
function showChangeMemberRole(libId, memberId, role) { openModal('修改成员角色', `<select id="member-role" style="width:100%"><option value="viewer" ${role==='viewer'?'selected':''}>只读</option><option value="editor" ${role==='editor'?'selected':''}>编辑</option><option value="manager" ${role==='manager'?'selected':''}>经理</option><option value="admin" ${role==='admin'?'selected':''}>库管理员</option></select><div class="modal-footer"><button class="btn btn-muted" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="changeMemberRole(${libId},${memberId})">保存</button></div>`); }
async function changeMemberRole(libId, memberId) { try { await api(`/libraries/${libId}/members/${memberId}`, { method:'PUT', body:{ role:document.getElementById('member-role').value } }); toast('已更新','success'); showLibMembers(libId); } catch(e){ toast(e.message,'error'); } }
async function removeMember(libId, memberId) { confirmLayer({ title:'移除成员', message:'确定移除该成员？', okText:'确认移除', onOk: async()=>{ await api(`/libraries/${libId}/members/${memberId}`, { method:'DELETE' }); toast('已移除','success'); showLibMembers(libId); }}); }

let selectedLibId = null, searchTimer;
async function loadCards() {
  const el = document.getElementById('page-cards');
  el.innerHTML = `<div class="toolbar"><h2 style="margin:0;flex:1">🃏 名片管理</h2><select id="card-lib-select" onchange="selectedLibId=this.value;loadCardList()"><option value="">选择名片库...</option></select><input class="search-input" id="card-search" placeholder="搜索姓名/电话/公司..." oninput="debounceSearch()"><button class="btn btn-primary" onclick="showCardEditor()">+ 新建名片</button></div><div class="card"><div id="cards-list">请选择名片库</div></div>`;
  const libs = await api('/libraries'); const sel = document.getElementById('card-lib-select'); libs.forEach(l => sel.innerHTML += `<option value="${l.id}">${escapeHtml(l.name)}（${roleLabel(l.role)}）</option>`);
}
function debounceSearch(){ clearTimeout(searchTimer); searchTimer=setTimeout(loadCardList,300); }
async function loadCardList() {
  const el = document.getElementById('cards-list'); if (!selectedLibId) return el.innerHTML='<p style="color:#999">请选择名片库</p>';
  try { const search = document.getElementById('card-search').value; const res = await api('/cards?' + new URLSearchParams({ libraryId:selectedLibId, pageSize:100, ...(search ? { search } : {}) })); const cards=res.data||[]; el.innerHTML = cards.length ? `<table><thead><tr><th>姓名</th><th>电话</th><th>邮箱</th><th>工作单位</th><th>职位</th><th>权限</th><th>操作</th></tr></thead><tbody>${cards.map(c => `<tr><td><strong>${escapeHtml(c.name)}</strong></td><td>${escapeHtml((c.phones||[c.phone]).filter(Boolean).join(' / ') || '-')}</td><td>${escapeHtml((c.emails||[c.email]).filter(Boolean).join(' / ') || '-')}</td><td>${escapeHtml(c.company||'-')}</td><td>${escapeHtml(c.position||'-')}</td><td><span class="badge badge-${c.role}">${roleLabel(c.role)}</span></td><td><button class="btn-sm outline" onclick="viewCard(${c.id})">详情</button>${c.actions?.canEdit?`<button class="btn-sm blue" onclick="showCardEditor(${c.id})">编辑</button>`:''}${c.actions?.canManageVisibility?`<button class="btn-sm outline" onclick="showCardVisibility(${c.id})">可见性</button>`:''}${c.actions?.canDelete?`<button class="btn-sm danger" onclick="deleteCard(${c.id})">删除</button>`:''}</td></tr>`).join('')}</tbody></table>` : '<p style="color:#999">暂无名片</p>'; } catch(e){ el.innerHTML=`<div class="error">${e.message}</div>`; }
}
async function viewCard(id) {
  const c = await api('/cards/'+id); const phones = c.phones || (c.phone ? [c.phone] : []); const emails = c.emails || (c.email ? [c.email] : []);
  openModal('名片详情', `<div class="detail-head"><div class="avatar-lg">${c.avatar ? `<img src="${escapeHtml(c.avatar)}">` : escapeHtml((c.name||'?').slice(0,1))}</div><div><div class="detail-name">${escapeHtml(c.name)}</div><div class="detail-sub">${escapeHtml(c.position||'')} ${c.company ? '@ '+escapeHtml(c.company) : ''}</div><div style="margin-top:6px"><span class="badge badge-${c.role}">${roleLabel(c.role)}</span></div></div></div><div class="info-list">${renderField('电话', phones)}${renderField('邮箱', emails)}${renderField('微信', c.wechat)}${renderField('工作单位', c.company)}${renderField('职位', c.position)}${renderField('级别', c.jobLevel)}${renderField('行业', c.industry)}${renderField('领域', c.field)}${renderField('性别', c.gender)}${renderField('住宅地址', c.residentialAddress)}${renderField('籍贯', c.birthplace)}${renderField('老家地址', c.hometownAddress)}${renderField('标签', c.tags)}${renderField('备注', c.remark)}</div>${renderArraySection('🎓 教育经历', c.educationBackground, e=>`<div class="exp-item"><strong>${escapeHtml(e.school||'')}</strong> ${escapeHtml(e.major||'')} ${escapeHtml(e.degree||'')}<br><small>${escapeHtml(e.startDate||'')} - ${escapeHtml(e.endDate||'')}</small></div>`)}${renderArraySection('💼 工作经历', c.workExperience, e=>`<div class="exp-item"><strong>${escapeHtml(e.company||'')}</strong> ${escapeHtml(e.position||'')} ${escapeHtml(e.department||'')}<br><small>${escapeHtml(e.startDate||'')} - ${escapeHtml(e.endDate||'')}</small><br>${escapeHtml(e.description||'')}</div>`)}<div class="modal-footer"><button class="btn btn-muted" onclick="closeModal()">关闭</button>${c.actions?.canEdit?`<button class="btn btn-primary" onclick="showCardEditor(${id})">编辑</button>`:''}</div>`, 'large');
}
function cardForm(c={}) { return `<div class="form-grid"><input class="input" id="card-name" placeholder="姓名 *" value="${escapeHtml(c.name||'')}"><input class="input" id="card-avatar" placeholder="照片 URL" value="${escapeHtml(c.avatar||'')}"><input class="input" id="card-phones" placeholder="电话，多个用逗号分隔" value="${escapeHtml((c.phones||[c.phone]).filter(Boolean).join(','))}"><input class="input" id="card-emails" placeholder="邮箱，多个用逗号分隔" value="${escapeHtml((c.emails||[c.email]).filter(Boolean).join(','))}"><input class="input" id="card-company" placeholder="工作单位" value="${escapeHtml(c.company||'')}"><input class="input" id="card-position" placeholder="职位" value="${escapeHtml(c.position||'')}"><input class="input" id="card-jobLevel" placeholder="级别" value="${escapeHtml(c.jobLevel||'')}"><input class="input" id="card-wechat" placeholder="微信" value="${escapeHtml(c.wechat||'')}"><textarea class="full" id="card-edu" placeholder='教育经历 JSON，如 [{"school":"清华","major":"计算机","degree":"本科"}]'>${escapeHtml(JSON.stringify(c.educationBackground||[]))}</textarea><textarea class="full" id="card-work" placeholder='工作经历 JSON，如 [{"company":"腾讯","position":"总监"}]'>${escapeHtml(JSON.stringify(c.workExperience||[]))}</textarea><textarea class="full" id="card-remark" placeholder="备注">${escapeHtml(c.remark||'')}</textarea></div>`; }
async function showCardEditor(id) { if (!selectedLibId && !id) return toast('请先选择名片库','error'); const c = id ? await api('/cards/'+id) : {}; openModal(id?'编辑名片':'新建名片', `${cardForm(c)}<div class="modal-footer"><button class="btn btn-muted" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="saveCard(${id||0})">保存</button></div>`, 'large'); }
async function saveCard(id) { const phones = document.getElementById('card-phones').value.split(',').map(s=>s.trim()).filter(Boolean); const emails = document.getElementById('card-emails').value.split(',').map(s=>s.trim()).filter(Boolean); let edu=[], work=[]; try{edu=JSON.parse(document.getElementById('card-edu').value||'[]');work=JSON.parse(document.getElementById('card-work').value||'[]')}catch{return toast('教育/工作经历 JSON 格式不对','error')} const body={ libraryId:selectedLibId, name:document.getElementById('card-name').value, avatar:document.getElementById('card-avatar').value, phone:phones[0]||'', phones, email:emails[0]||'', emails, company:document.getElementById('card-company').value, position:document.getElementById('card-position').value, jobLevel:document.getElementById('card-jobLevel').value, wechat:document.getElementById('card-wechat').value, educationBackground:edu, workExperience:work, remark:document.getElementById('card-remark').value }; try{ await api(id?`/cards/${id}`:'/cards',{method:id?'PUT':'POST',body}); toast('已保存','success'); closeModal(); loadCardList(); }catch(e){toast(e.message,'error')} }
async function deleteCard(id) { confirmLayer({ title:'删除名片', tone:'soft', message:'删除是低频操作。确定删除这张名片？', okText:'确认删除', onOk: async()=>{ await api('/cards/'+id,{method:'DELETE'}); toast('已删除','success'); loadCardList(); }}); }
async function showCardVisibility(id) { const vis = await api(`/cards/${id}/visibility`).catch(()=>[]); const map={}; vis.forEach(v=>map[v.fieldName]=v.visibility); openModal('字段可见性', `<div class="field-grid">${Object.entries(LIB_FIELD_LABELS).map(([k,v])=>`<label class="field-check">${v}<select data-field="${k}" style="width:100%;margin-top:6px"><option value="public" ${map[k]==='public'?'selected':''}>公开</option><option value="admin_only" ${map[k]==='admin_only'?'selected':''}>仅管理员</option><option value="hidden" ${map[k]==='hidden'?'selected':''}>隐藏</option></select></label>`).join('')}</div><div class="modal-footer"><button class="btn btn-muted" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="saveCardVisibility(${id})">保存</button></div>`, 'large'); }
async function saveCardVisibility(id){ const fields=Array.from(document.querySelectorAll('#modal-body select[data-field]')).map(s=>({fieldName:s.dataset.field,visibility:s.value})); try{await api(`/cards/${id}/visibility`,{method:'PUT',body:{fields}});toast('已保存','success');closeModal();}catch(e){toast(e.message,'error')} }

async function loadSettings() { const el=document.getElementById('page-settings'); el.innerHTML=`<h2>⚙️ 设置</h2><div class="tabs"><div class="tab active" onclick="showSettingsTab('profile',this)">个人设置</div>${currentUser.role==='super_admin'?`<div class="tab" onclick="showSettingsTab('users',this)">用户管理</div>`:''}</div><div id="settings-body"></div>`; showSettingsTab('profile'); }
function showSettingsTab(name, tabEl){ document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active')); tabEl?.classList.add('active'); if(name==='users') loadUsersInSettings(); else loadProfileSettings(); }
async function loadProfileSettings(){ const me=await api('/auth/me'); document.getElementById('settings-body').innerHTML=`<div class="card"><div class="card-title">个人资料</div><input class="input" id="me-nick" value="${escapeHtml(me.nickname||'')}" placeholder="昵称"><input class="input" id="me-phone" value="${escapeHtml(me.phone||'')}" placeholder="手机"><button class="btn btn-primary" onclick="saveMe()">保存资料</button></div><div class="card"><div class="card-title">修改密码</div><input class="input" type="password" id="old-pass" placeholder="旧密码"><input class="input" type="password" id="new-pass" placeholder="新密码，至少6位"><button class="btn btn-blue" onclick="changePassword()">修改密码</button></div>`; }
async function saveMe(){ try{const me=await api('/auth/me',{method:'PUT',body:{nickname:document.getElementById('me-nick').value,phone:document.getElementById('me-phone').value}}); localStorage.setItem('user',JSON.stringify(me)); currentUser=me; document.getElementById('user-info').textContent=me.nickname||me.username; toast('已保存','success')}catch(e){toast(e.message,'error')} }
async function changePassword(){ try{await api('/auth/password',{method:'PUT',body:{oldPassword:document.getElementById('old-pass').value,newPassword:document.getElementById('new-pass').value}}); toast('密码已修改，请重新登录','success'); setTimeout(doLogout,800);}catch(e){toast(e.message,'error')} }
async function loadUsersInSettings(){ const users=await api('/auth/users'); document.getElementById('settings-body').innerHTML=`<div class="toolbar"><button class="btn btn-primary" onclick="showAddUser()">+ 新建用户</button></div><div class="card"><table><thead><tr><th>ID</th><th>用户名</th><th>昵称</th><th>角色</th><th>操作</th></tr></thead><tbody>${users.map(u=>`<tr><td>${u.id}</td><td>${escapeHtml(u.username)}</td><td>${escapeHtml(u.nickname||'-')}</td><td><span class="badge badge-${u.role}">${roleLabel(u.role)}</span></td><td><button class="btn-sm outline" onclick="editUser(${u.id})">编辑</button>${u.role!=='super_admin'&&u.id!==currentUser.id?`<button class="btn-sm danger" onclick="deleteUser(${u.id})">删除</button>`:''}</td></tr>`).join('')}</tbody></table></div>`; }
function showAddUser(){ openModal('新建用户', `<input class="input" id="u-name" placeholder="用户名"><input class="input" id="u-nick" placeholder="昵称"><input class="input" type="password" id="u-pass" placeholder="密码"><select id="u-role" style="width:100%"><option value="user">普通用户</option><option value="super_admin">超级管理员</option></select><div class="modal-footer"><button class="btn btn-muted" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="createUser()">创建</button></div>`); }
async function createUser(){ try{await api('/auth/users',{method:'POST',body:{username:document.getElementById('u-name').value,nickname:document.getElementById('u-nick').value,password:document.getElementById('u-pass').value,role:document.getElementById('u-role').value}}); toast('已创建','success'); closeModal(); loadUsersInSettings();}catch(e){toast(e.message,'error')} }
async function editUser(id){ const users=await api('/auth/users'); const u=users.find(x=>x.id===id); openModal('编辑用户', `<input class="input" id="u-nick" value="${escapeHtml(u.nickname||'')}" placeholder="昵称"><input class="input" type="password" id="u-pass" placeholder="重置密码，留空不改"><select id="u-role" style="width:100%"><option value="user" ${u.role==='user'?'selected':''}>普通用户</option><option value="super_admin" ${u.role==='super_admin'?'selected':''}>超级管理员</option></select><div class="modal-footer"><button class="btn btn-muted" onclick="closeModal()">取消</button><button class="btn btn-primary" onclick="saveUser(${id})">保存</button></div>`); }
async function saveUser(id){ const body={nickname:document.getElementById('u-nick').value,role:document.getElementById('u-role').value}; const p=document.getElementById('u-pass').value; if(p) body.password=p; try{await api('/auth/users/'+id,{method:'PUT',body}); toast('已保存','success'); closeModal(); loadUsersInSettings();}catch(e){toast(e.message,'error')} }
async function deleteUser(id){ confirmLayer({title:'删除用户',tone:'soft',message:'确定删除该用户？相关名片库和名片可能受影响。',okText:'确认删除',onOk:async()=>{await api('/auth/users/'+id,{method:'DELETE'});toast('已删除','success');loadUsersInSettings();}}); }

async function loadDuplicates(){ document.getElementById('page-duplicates').innerHTML='<div class="card"><p>查重模块保留原接口，下一步可继续细化交互。</p></div>'; }
async function loadImport(){ document.getElementById('page-import').innerHTML='<div class="card"><p>导入导出模块保留原接口，下一步可继续细化交互。</p></div>'; }
